export type GalleryBranch = 'all' | 'mirpur' | 'dhanmondi' | 'lalbagh' | 'female';

export interface GalleryItem {
  id: string;
  title: string;
  branch: 'mirpur' | 'dhanmondi' | 'lalbagh' | 'female';
  branchLabel: string;
  imageSrc: string; // e.g., '/images/gallery/mirpur-view.webp'
  alt: string;
  width?: number;
  height?: number;
  tag?: string;
  featured?: boolean;
}

export interface GalleryFilter {
  id: GalleryBranch;
  label: string;
  count?: number;
}

export const GALLERY_FILTERS: { id: GalleryBranch; label: string }[] = [
  { id: 'all', label: 'All' },
  { id: 'mirpur', label: 'Mirpur Branch' },
  { id: 'dhanmondi', label: 'Dhanmondi Branch' },
  { id: 'lalbagh', label: 'Lalbagh Branch' },
  { id: 'female', label: 'Female Zone' },
];

export const GALLERY_ITEMS: GalleryItem[] = [
  {
    id: '1',
    title: 'Lift-11 Panoramic View & Cardio Deck',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/mirpur-view.webp',
    alt: 'Mirpur Lift 11 Gym View',
    width: 1200,
    height: 1800,
    tag: 'Panoramic Deck',
    featured: true,
  },
  {
    id: '2',
    title: 'Heavy Biomechanics & Leg Press Area',
    branch: 'dhanmondi',
    branchLabel: 'Dhanmondi Outlet',
    imageSrc: '/images/gallery/dhanmondi-leg-press.webp',
    alt: 'Dhanmondi Biomechanics Equipment',
    width: 720,
    height: 960,
    tag: 'Biomechanics',
  },
  {
    id: '3',
    title: "Dedicated Women's Private Training Slot",
    branch: 'female',
    branchLabel: 'Female Zone',
    imageSrc: '/images/gallery/female-training-zone.webp',
    alt: 'Female Only Workout Hours Rayhan Fitness',
    width: 1200,
    height: 900,
    tag: 'Women Only',
    featured: true,
  },
  {
    id: '4',
    title: 'Championship Free Weight & Dumbbell Zone',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/lalbagh-weights.webp',
    alt: 'Lalbagh Free Weights and Bodybuilding Section',
    width: 960,
    height: 724,
    tag: 'Free Weights',
    featured: true,
  },
  {
    id: '5',
    title: 'High-Performance Spin & Cardio Studio',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/mirpur-cardio.webp',
    alt: 'Mirpur Branch Cardio and Spin Bike Arena',
    width: 720,
    height: 960,
    tag: 'Cardio Deck',
  },
  {
    id: '6',
    title: 'Certified Female & Elite Coaching Staff',
    branch: 'female',
    branchLabel: 'Female Zone',
    imageSrc: '/images/gallery/female-coaching-staff.webp',
    alt: 'Rayhan Fitness Certified Female and Male Trainers',
    width: 1200,
    height: 1100,
    tag: 'Certified Staff',
  },
  {
    id: '7',
    title: 'Matrix Multi-Station Cable Tower & Arena',
    branch: 'dhanmondi',
    branchLabel: 'Dhanmondi Outlet',
    imageSrc: '/images/gallery/dhanmondi-cable-tower.webp',
    alt: 'Matrix Multi Station Strength Rig Dhanmondi',
    width: 1200,
    height: 800,
    tag: 'Strength Rig',
    featured: true,
  },
  {
    id: '8',
    title: 'National Championship Bodybuilding Lineup',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/lalbagh-champions.webp',
    alt: 'Championship Medalists Trained at Rayhan Fitness Flagship',
    width: 1200,
    height: 822,
    tag: 'Champions',
  },
  {
    id: '9',
    title: 'Team Rayhan Fitness: Championship Coaching Roster',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/team-rayhan-fitness.webp',
    alt: 'Rayhan Fitness Certified Coaches Team',
    width: 1200,
    height: 480,
    tag: 'Full Roster',
    featured: true,
  },
  {
    id: '10',
    title: 'Championship Victory & Member Community',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/lalbagh-community.webp',
    alt: 'Rayhan Fitness Community Celebrating National Victory',
    width: 1200,
    height: 800,
    tag: 'Community',
  },
  {
    id: '11',
    title: 'Vibrant Lift-11 Member Community & Atmosphere',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/mirpur-community.webp',
    alt: 'Mirpur Outlet Members and Community Celebration',
    width: 1200,
    height: 900,
    tag: 'Atmosphere',
  },
  {
    id: '12',
    title: 'Inclusive & Welcoming Training Culture',
    branch: 'female',
    branchLabel: 'Female Zone',
    imageSrc: '/images/gallery/female-welcome-culture.webp',
    alt: 'Female and Male Members Welcomed at Rayhan Fitness',
    width: 1200,
    height: 900,
    tag: 'Safe Culture',
  },
  {
    id: '13',
    title: 'VIP Member Welcome & Dedicated Gear',
    branch: 'dhanmondi',
    branchLabel: 'Dhanmondi Outlet',
    imageSrc: '/images/gallery/dhanmondi-member-welcome.webp',
    alt: 'Member Induction and Gear at Dhanmondi Branch',
    width: 780,
    height: 1040,
    tag: 'VIP Care',
  },
  {
    id: '14',
    title: 'Elite Physique Conditioning & Posing Stage',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/lalbagh-physique.webp',
    alt: 'Bodybuilders Training at Lalbagh Flagship',
    width: 1200,
    height: 1600,
    tag: 'Conditioning',
  },
  {
    id: '15',
    title: 'Head Coach Rayhan: Leading by Practice',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/coach-rayhan-training.webp',
    alt: 'Head Coach Rayhan Training in Flagship Gym',
    width: 1200,
    height: 1600,
    tag: 'Master Coach',
  },
  {
    id: '16',
    title: 'Pro-Athlete Mentorship & Prep Coaching',
    branch: 'dhanmondi',
    branchLabel: 'Dhanmondi Outlet',
    imageSrc: '/images/gallery/dhanmondi-pro-mentorship.webp',
    alt: 'Pro Bodybuilder Training Under Coach Rayhan',
    width: 1200,
    height: 800,
    tag: 'Mentorship',
  },
  {
    id: '17',
    title: 'Proven Client Transformation: Fat Loss to Shredded',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/transformation-client-1.webp',
    alt: 'Rayhan Fitness Member Body Transformation Result',
    width: 1200,
    height: 1036,
    tag: 'Results',
  },
  {
    id: '18',
    title: '12-Week Transformation: Lean Muscle Building',
    branch: 'dhanmondi',
    branchLabel: 'Dhanmondi Outlet',
    imageSrc: '/images/gallery/transformation-client-2.webp',
    alt: 'Client Transformation 12 Week Program Rayhan Fitness',
    width: 1200,
    height: 1093,
    tag: 'Results',
  },
  {
    id: '19',
    title: 'National Bodybuilding Federation Medals & Accolades',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/coach-rayhan-medals.webp',
    alt: 'National Medals Held by Coach Rayhan',
    width: 1200,
    height: 1600,
    tag: 'Accolades',
  },
  {
    id: '20',
    title: 'National Stage Judging & Federation Leadership',
    branch: 'lalbagh',
    branchLabel: 'Lalbagh Outlet',
    imageSrc: '/images/gallery/national-stage-judging.webp',
    alt: 'Coach Rayhan Judging at National Bodybuilding Championship',
    width: 1200,
    height: 800,
    tag: 'Federation',
  },
  {
    id: '21',
    title: 'Pro Physique Standards & Vacuum Mastery',
    branch: 'female',
    branchLabel: 'Female Zone',
    imageSrc: '/images/gallery/coach-rayhan-posing.webp',
    alt: 'Head Coach Rayhan Physique and Conditioning',
    width: 1200,
    height: 1587,
    tag: 'Pro Standard',
  },
  {
    id: '22',
    title: 'Best Gym in Bangladesh: Premier Fitness Network',
    branch: 'mirpur',
    branchLabel: 'Mirpur Outlet',
    imageSrc: '/images/gallery/best-gym-bangladesh.webp',
    alt: 'Best Gym in Bangladesh Rayhan Fitness Showcase',
    width: 1200,
    height: 675,
    tag: 'National Award',
  },
];
